/* FIND IT! - photo-submit.js
   Processing, preview, submit and pass. Requires api.js, photo-state.js, photos.js. */
function getStoredPlayerGame(){for(const k of["findItGame","findItPlayerGame"]){try{const r=localStorage.getItem(k);if(!r)continue;const g=JSON.parse(r);if(g&&(g.gameCode||g.GameCode||g.code))return g;}catch(e){console.warn("PHOTO SUBMIT: game storage",e);}}return null;}
function getStoredPlayer(){for(const k of["findItCurrentPlayer","findItPlayer"]){try{const r=localStorage.getItem(k);if(!r)continue;const p=JSON.parse(r);if(p&&(p.playerId||p.PlayerID||p.id))return p;}catch(e){console.warn("PHOTO SUBMIT: player storage",e);}}return null;}
function getPhotoPlayer(){if(typeof window.getCurrentPlayer==="function"){try{const p=window.getCurrentPlayer();if(p&&(p.playerId||p.PlayerID||p.id))return p;}catch(e){console.warn("PHOTO SUBMIT: getCurrentPlayer",e);}}return getStoredPlayer();}
function getPhotoGame(){if(typeof window.getPlayerGame==="function"){try{const g=window.getPlayerGame();if(g&&(g.gameCode||g.GameCode||g.code))return g;}catch(e){console.warn("PHOTO SUBMIT: getPlayerGame",e);}}const g=getStoredPlayerGame();if(g)return g;const p=getPhotoPlayer();if(p&&(p.gameCode||p.GameCode))return{gameCode:p.gameCode||p.GameCode};const c=FindItPhoto.getCategory();return c&&(c.gameCode||c.GameCode)?{gameCode:c.gameCode||c.GameCode}:null;}
function getPhotoCategory(){let c=FindItPhoto.getCategory();if(c)return c;if(typeof window.getPlayerCurrentCategory==="function"){try{c=window.getPlayerCurrentCategory();if(c){FindItPhoto.setCategory(c);return c;}}catch(e){console.warn("PHOTO SUBMIT: current category",e);}}if(window.playerCurrentCategory){FindItPhoto.setCategory(window.playerCurrentCategory);return FindItPhoto.getCategory();}try{const r=localStorage.getItem("findItCurrentCategory");if(r){c=JSON.parse(r);FindItPhoto.setCategory(c);return c;}}catch(e){console.warn("PHOTO SUBMIT: category storage",e);}return null;}
function loadPhotoImage(src){return new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=src;});}
function calculatePhotoDimensions(w,h,max){if(w<=max&&h<=max)return{width:w,height:h};const s=Math.min(max/w,max/h);return{width:Math.round(w*s),height:Math.round(h*s)};}
function approximateBase64Bytes(b){if(!b)return 0;const i=b.indexOf(","),d=i>=0?b.substring(i+1):b;return Math.floor(d.length*.75);}
async function processPhotoData(src){if(!src){setPhotoMessage("No photo selected.");return;}try{if(FindItPhoto.setStage)FindItPhoto.setStage("PROCESSING");setPhotoMessage("Processing photo...");const i=await loadPhotoImage(src),d=calculatePhotoDimensions(i.naturalWidth||i.width,i.naturalHeight||i.height,1200),c=document.createElement("canvas");c.width=d.width;c.height=d.height;const x=c.getContext("2d");if(!x)throw new Error("Could not create image canvas.");x.drawImage(i,0,0,d.width,d.height);let q=.78,o=c.toDataURL("image/jpeg",q);while(approximateBase64Bytes(o)>350*1024&&q>.45){q-=.05;o=c.toDataURL("image/jpeg",q);}FindItPhoto.setProcessedPhoto(o);showProcessedPhoto(o);setPhotoMessage("Photo ready. Check the preview, then submit or choose another photo.");}catch(e){console.error("PHOTO SUBMIT: processing",e);FindItPhoto.clearPhoto();if(FindItPhoto.setStage)FindItPhoto.setStage("OPTIONS");if(typeof window.showPhotoOptions==="function")window.showPhotoOptions();setPhotoMessage("Could not process that photo. Please try again.");}}
function showProcessedPhoto(data){const p=photoElement("photoPreview");if(!p)return console.error("PHOTO SUBMIT: photoPreview not found");p.src=data;if(typeof window.showPhotoPreviewControls==="function")window.showPhotoPreviewControls();else{photoHideElement("cameraContainer");photoHideElement("passCategoryButton");photoShowElement("photoPreviewContainer");photoShowElement("submitPhotoButton");photoShowElement("takePhotoButton");photoShowElement("choosePhotoButton");}if(FindItPhoto.setStage)FindItPhoto.setStage("PREVIEW");}
function resolvePhotoSubmissionFields(){const g=getPhotoGame(),p=getPhotoPlayer(),c=getPhotoCategory();return{gameCode:(g&&(g.gameCode||g.GameCode||g.code))||(p&&(p.gameCode||p.GameCode))||(c&&(c.gameCode||c.GameCode))||"",playerId:(p&&(p.playerId||p.PlayerID||p.id))||"",playerName:(p&&(p.playerName||p.PlayerName||p.name))||"",categoryId:(c&&(c.categoryId||c.CategoryID||c.id))||"",categoryNumber:(c&&(c.categoryNumber||c.CategoryNumber||c.number))||""};}
async function submitPhoto(){if(FindItPhoto.getSubmissionBusy())return;const stage=FindItPhoto.getStage?FindItPhoto.getStage():"PREVIEW";if(stage!=="PREVIEW")return setPhotoMessage("Please wait until the photo preview is ready.");const photoData=FindItPhoto.getProcessedPhoto();if(!photoData)return setPhotoMessage("Please take or choose a photo first.");const f=resolvePhotoSubmissionFields();if(!f.gameCode)return setPhotoMessage("Game information is missing.");if(!f.playerId)return setPhotoMessage("Player information is missing.");if(!f.categoryId)return setPhotoMessage("Challenge information is missing.");FindItPhoto.setSubmissionBusy(true);if(FindItPhoto.setStage)FindItPhoto.setStage("SUBMITTING");const ids=["submitPhotoButton","passCategoryButton","takePhotoButton","choosePhotoButton","uploadBackButton"];ids.forEach(id=>{const e=photoElement(id);if(e)e.disabled=true;});const sb=photoElement("submitPhotoButton");if(sb)sb.textContent="Submitting...";setPhotoMessage("Submitting photo...");try{const r=await apiPost("submitEntry",{...f,photoData});if(!r||r.success===false)throw new Error(r&&r.error?r.error:"Photo submission failed.");FindItPhoto.reset();stopPhotoCamera();setPhotoMessage("Challenge complete!");if(typeof window.showScreen==="function")window.showScreen("collectionScreen");if(typeof window.refreshPlayerCategories==="function")setTimeout(()=>window.refreshPlayerCategories(),100);}catch(e){console.error("PHOTO SUBMIT: submit",e);FindItPhoto.setSubmissionBusy(false);if(FindItPhoto.setStage)FindItPhoto.setStage("PREVIEW");if(typeof window.showPhotoPreviewControls==="function")window.showPhotoPreviewControls();setPhotoMessage(e.message||"Could not submit photo. Your photo is still ready to retry.");return;}finally{FindItPhoto.setSubmissionBusy(false);ids.forEach(id=>{const e=photoElement(id);if(e)e.disabled=false;});}}
async function passPhotoCategory(){if(FindItPhoto.getSubmissionBusy())return;const stage=FindItPhoto.getStage?FindItPhoto.getStage():"OPTIONS";if(stage!=="OPTIONS")return setPhotoMessage("Return to the photo options before passing this challenge.");const f=resolvePhotoSubmissionFields();if(!f.gameCode)return setPhotoMessage("Game information is missing.");if(!f.playerId)return setPhotoMessage("Player information is missing.");if(!f.categoryId)return setPhotoMessage("Challenge information is missing.");if(!window.confirm("Pass this challenge?"))return;FindItPhoto.setSubmissionBusy(true);const pb=photoElement("passCategoryButton");if(pb){pb.disabled=true;pb.textContent="Passing...";}setPhotoMessage("Passing challenge...");try{const r=await apiPost("submitPass",f);if(!r||r.success===false)throw new Error(r&&r.error?r.error:"Pass failed.");FindItPhoto.reset();stopPhotoCamera();setPhotoMessage("Challenge passed.");if(typeof window.showScreen==="function")window.showScreen("collectionScreen");if(typeof window.refreshPlayerCategories==="function")setTimeout(()=>window.refreshPlayerCategories(),100);}catch(e){console.error("PHOTO SUBMIT: pass",e);setPhotoMessage(e.message||"Could not pass challenge.");if(pb){pb.disabled=false;pb.textContent="Pass This Challenge";}}finally{FindItPhoto.setSubmissionBusy(false);}}
window.processPhotoData=processPhotoData;window.showProcessedPhoto=showProcessedPhoto;window.submitPhoto=submitPhoto;window.passPhotoCategory=passPhotoCategory;window.getPhotoGame=getPhotoGame;window.getPhotoPlayer=getPhotoPlayer;window.approximateBase64Bytes=approximateBase64Bytes;console.log("Find It! photo-submit.js ready");