/* FIND IT! - photos.js
   Camera, capture and photo screen UI. Requires photo-state.js and photo-submit.js. */
function photoElement(id){return document.getElementById(id);}
function photoShowElement(id){const e=photoElement(id);if(!e)return;e.classList.remove("hidden");e.style.display="";}
function photoHideElement(id){const e=photoElement(id);if(!e)return;e.classList.add("hidden");e.style.display="none";}
function setPhotoMessage(m){const e=photoElement("uploadMessage");if(e)e.textContent=m||"";}
function stopPhotoCamera(){const s=FindItPhoto.getStream();if(s){try{s.getTracks().forEach(t=>t.stop());}catch(e){console.warn("PHOTOS: stop camera",e);}}FindItPhoto.setStream(null);const v=photoElement("cameraPreview");if(v){try{v.pause();}catch(_){}v.srcObject=null;}}
function setPhotoButtonLabel(id,label){const e=photoElement(id);if(e)e.textContent=label;}
function setPhotoStage(stage){if(FindItPhoto&&typeof FindItPhoto.setStage==="function")FindItPhoto.setStage(stage);}
function clearPhotoImage(){stopPhotoCamera();FindItPhoto.clearPhoto();const i=photoElement("photoInput");if(i)i.value="";const p=photoElement("photoPreview");if(p)p.src="";}
function showPhotoOptions(){stopPhotoCamera();setPhotoStage("OPTIONS");["cameraContainer","capturePhotoButton","closeCameraButton","photoPreviewContainer","submitPhotoButton"].forEach(photoHideElement);["takePhotoButton","choosePhotoButton","passCategoryButton","uploadBackButton"].forEach(photoShowElement);setPhotoButtonLabel("takePhotoButton","📷 Take Photo");setPhotoButtonLabel("choosePhotoButton","Choose Photo From Device");const b=photoElement("passCategoryButton");if(b){b.disabled=false;b.textContent="Pass This Challenge";}const s=photoElement("submitPhotoButton");if(s){s.disabled=false;s.textContent="Submit Photo";}setPhotoMessage("");}
function showPhotoPreviewControls(){setPhotoStage("PREVIEW");["cameraContainer","capturePhotoButton","closeCameraButton","passCategoryButton"].forEach(photoHideElement);["photoPreviewContainer","submitPhotoButton","takePhotoButton","choosePhotoButton","uploadBackButton"].forEach(photoShowElement);setPhotoButtonLabel("takePhotoButton","📷 Take Photo Again");setPhotoButtonLabel("choosePhotoButton","Choose Another Photo");const s=photoElement("submitPhotoButton");if(s){s.disabled=false;s.textContent="Submit Photo";}}
function resetPhotoUI(){clearPhotoImage();showPhotoOptions();}
function resetPhotoUpload(){resetPhotoUI();}
function updatePhotoChallengeInfo(c){if(!c)return;const n=c.categoryNumber||c.CategoryNumber||c.number||"",name=c.categoryName||c.CategoryName||c.name||"",d=c.description||c.Description||"";const t=photoElement("uploadCategoryTitle"),ne=photoElement("uploadCategoryNumber"),nae=photoElement("uploadCategoryName"),de=photoElement("uploadCategoryDescription");if(t)t.textContent="Find it!";if(ne)ne.textContent=n?"Challenge "+n:"Challenge";if(nae)nae.textContent=name;if(de)de.textContent=d;}
function setPhotoCategory(c){if(!c)return;FindItPhoto.setCategory(c);updatePhotoChallengeInfo(c);}
function openPhotoUpload(category){console.log("PHOTOS: opening options",category);if(!category){setPhotoMessage("Challenge information is missing.");return;}FindItPhoto.setCategory(category);try{localStorage.setItem("findItCurrentCategory",JSON.stringify(category));}catch(e){console.warn("PHOTOS: persist category",e);}resetPhotoUI();FindItPhoto.setCategory(category);updatePhotoChallengeInfo(category);if(typeof window.showScreen==="function")window.showScreen("photoUploadScreen");else photoShowElement("photoUploadScreen");showPhotoOptions();}
function closePhotoUpload(){stopPhotoCamera();FindItPhoto.reset();const i=photoElement("photoInput");if(i)i.value="";const p=photoElement("photoPreview");if(p)p.src="";if(typeof window.showScreen==="function")window.showScreen("collectionScreen");if(typeof window.refreshPlayerCategories==="function")window.refreshPlayerCategories();}
async function startPhotoCamera(){if(FindItPhoto.getSubmissionBusy())return false;if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia){setPhotoMessage("Camera is not available. Please choose a photo instead.");return false;}try{stopPhotoCamera();setPhotoStage("CAMERA");const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}},audio:false});const screen=photoElement("photoUploadScreen");if(!screen||(!screen.classList.contains("active")&&screen.style.display==="none")){s.getTracks().forEach(t=>t.stop());showPhotoOptions();return false;}FindItPhoto.setStream(s);const v=photoElement("cameraPreview");if(!v)throw new Error("Camera preview element not found.");v.srcObject=s;v.setAttribute("playsinline","");v.setAttribute("autoplay","");v.muted=true;await v.play();["takePhotoButton","choosePhotoButton","passCategoryButton"].forEach(photoHideElement);["cameraContainer","capturePhotoButton","closeCameraButton"].forEach(photoShowElement);setPhotoMessage("Camera ready.");return true;}catch(e){console.error("PHOTOS: camera",e);stopPhotoCamera();showPhotoOptions();setPhotoMessage("Could not open the camera. Please choose a photo instead.");return false;}}
function capturePhoto(){const v=photoElement("cameraPreview");if(!v)return setPhotoMessage("Camera preview not found.");if(!v.videoWidth||!v.videoHeight)return setPhotoMessage("Camera is not ready yet.");const c=document.createElement("canvas");c.width=v.videoWidth;c.height=v.videoHeight;const x=c.getContext("2d");if(!x)return setPhotoMessage("Could not capture the photo.");x.drawImage(v,0,0,c.width,c.height);stopPhotoCamera();const raw=c.toDataURL("image/jpeg",.9);FindItPhoto.setOriginalPhoto(raw);setPhotoStage("PROCESSING");["cameraContainer","capturePhotoButton","closeCameraButton","takePhotoButton","choosePhotoButton","passCategoryButton","submitPhotoButton"].forEach(photoHideElement);setPhotoMessage("Processing photo...");if(typeof window.processPhotoData!=="function")return setPhotoMessage("Photo processing is not available.");window.processPhotoData(raw);}
function openPhotoFilePicker(){if(FindItPhoto.getSubmissionBusy())return;const i=photoElement("photoInput");if(!i)return;i.value="";i.click();}
function handlePhotoFile(e){const i=e&&e.target?e.target:photoElement("photoInput");if(!i||!i.files||!i.files.length)return;const f=i.files[0];if(!f.type||!f.type.startsWith("image/"))return setPhotoMessage("Please choose an image.");const r=new FileReader();r.onload=ev=>{const raw=ev.target.result;FindItPhoto.setOriginalPhoto(raw);setPhotoStage("PROCESSING");["takePhotoButton","choosePhotoButton","passCategoryButton","submitPhotoButton"].forEach(photoHideElement);setPhotoMessage("Processing photo...");if(typeof window.processPhotoData==="function")window.processPhotoData(raw);else setPhotoMessage("Photo processing is not available.");};r.onerror=()=>setPhotoMessage("Could not read that photo.");r.readAsDataURL(f);}
function retakePhoto(){if(FindItPhoto.getSubmissionBusy())return;clearPhotoImage();setPhotoMessage("");startPhotoCamera();}
function chooseAnotherPhoto(){if(FindItPhoto.getSubmissionBusy())return;openPhotoFilePicker();}
function cancelPhotoCamera(){stopPhotoCamera();showPhotoOptions();}
function setupPhotoButtons(){const bind=(id,fn)=>{const e=photoElement(id);if(e)e.onclick=ev=>{ev.preventDefault();fn();};};bind("takePhotoButton",()=>{const stage=FindItPhoto.getStage?FindItPhoto.getStage():"OPTIONS";if(stage==="PREVIEW")retakePhoto();else startPhotoCamera();});bind("choosePhotoButton",()=>{const stage=FindItPhoto.getStage?FindItPhoto.getStage():"OPTIONS";if(stage==="PREVIEW")chooseAnotherPhoto();else openPhotoFilePicker();});bind("capturePhotoButton",capturePhoto);bind("closeCameraButton",cancelPhotoCamera);bind("uploadBackButton",closePhotoUpload);bind("submitPhotoButton",()=>{if(typeof window.submitPhoto==="function")window.submitPhoto();});bind("passCategoryButton",()=>{if(typeof window.passPhotoCategory==="function")window.passPhotoCategory();});const i=photoElement("photoInput");if(i)i.onchange=handlePhotoFile;}
document.addEventListener("DOMContentLoaded",()=>{console.log("Find It! photos.js ready");setupPhotoButtons();resetPhotoUI();});
window.openPhotoUpload=openPhotoUpload;window.closePhotoUpload=closePhotoUpload;window.startPhotoCamera=startPhotoCamera;window.stopPhotoCamera=stopPhotoCamera;window.capturePhoto=capturePhoto;window.openPhotoFilePicker=openPhotoFilePicker;window.handlePhotoFile=handlePhotoFile;window.retakePhoto=retakePhoto;window.chooseAnotherPhoto=chooseAnotherPhoto;window.resetPhotoUpload=resetPhotoUpload;window.resetPhotoUI=resetPhotoUI;window.showPhotoOptions=showPhotoOptions;window.showPhotoPreviewControls=showPhotoPreviewControls;window.setPhotoCategory=setPhotoCategory;window.getPhotoCategory=()=>FindItPhoto.getCategory();