/* FIND IT! - photos.js
   Camera, capture and photo screen UI. Requires photo-state.js and photo-submit.js. */
function photoElement(id){return document.getElementById(id);}
function photoShowElement(id){const e=photoElement(id);if(!e)return;e.classList.remove("hidden");e.style.display="";}
function photoHideElement(id){const e=photoElement(id);if(!e)return;e.classList.add("hidden");e.style.display="none";}
function setPhotoMessage(m){const e=photoElement("uploadMessage");if(e)e.textContent=m||"";}
function stopPhotoCamera(){const s=FindItPhoto.getStream();if(s){try{s.getTracks().forEach(t=>t.stop());}catch(e){console.warn("PHOTOS: stop camera",e);}}FindItPhoto.setStream(null);const v=photoElement("cameraPreview");if(v){try{v.pause();}catch(_){}v.srcObject=null;}}
function resetPhotoUI(){stopPhotoCamera();FindItPhoto.clearPhoto();const i=photoElement("photoInput");if(i)i.value="";const p=photoElement("photoPreview");if(p)p.src="";["cameraContainer","photoPreviewContainer","capturePhotoButton","closeCameraButton","submitPhotoButton"].forEach(photoHideElement);["takePhotoButton","choosePhotoButton"].forEach(photoShowElement);const b=photoElement("passCategoryButton");if(b){b.disabled=false;b.textContent="Pass This Challenge";}setPhotoMessage("");}
function resetPhotoUpload(){resetPhotoUI();}
function updatePhotoChallengeInfo(c){if(!c)return;const n=c.categoryNumber||c.CategoryNumber||c.number||"",name=c.categoryName||c.CategoryName||c.name||"",d=c.description||c.Description||"";const t=photoElement("uploadCategoryTitle"),ne=photoElement("uploadCategoryNumber"),nae=photoElement("uploadCategoryName"),de=photoElement("uploadCategoryDescription");if(t)t.textContent="Find it!";if(ne)ne.textContent=n;if(nae)nae.textContent=name;if(de)de.textContent=d;}
function setPhotoCategory(c){if(!c)return;FindItPhoto.setCategory(c);updatePhotoChallengeInfo(c);}
function openPhotoUpload(category){console.log("PHOTOS: opening",category);if(!category){setPhotoMessage("Challenge information is missing.");return;}FindItPhoto.setCategory(category);try{localStorage.setItem("findItCurrentCategory",JSON.stringify(category));}catch(e){console.warn("PHOTOS: persist category",e);}resetPhotoUI();FindItPhoto.setCategory(category);updatePhotoChallengeInfo(category);if(typeof window.showScreen==="function")window.showScreen("photoUploadScreen");else photoShowElement("photoUploadScreen");["takePhotoButton","choosePhotoButton"].forEach(photoShowElement);["cameraContainer","capturePhotoButton","closeCameraButton","photoPreviewContainer","submitPhotoButton"].forEach(photoHideElement);requestAnimationFrame(()=>{if(FindItPhoto.getCategory()!==category)return console.warn("PHOTOS: challenge changed before camera start");startPhotoCamera();});}
function closePhotoUpload(){stopPhotoCamera();resetPhotoUI();if(typeof window.showScreen==="function")window.showScreen("collectionScreen");if(typeof window.refreshPlayerCategories==="function")window.refreshPlayerCategories();}
async function startPhotoCamera(){if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia){setPhotoMessage("Camera is not available. Please choose a photo instead.");return false;}try{stopPhotoCamera();const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}},audio:false});const screen=photoElement("photoUploadScreen");if(!screen||(!screen.classList.contains("active")&&screen.style.display==="none")){s.getTracks().forEach(t=>t.stop());return false;}FindItPhoto.setStream(s);const v=photoElement("cameraPreview");if(!v)throw new Error("Camera preview element not found.");v.srcObject=s;v.setAttribute("playsinline","");v.setAttribute("autoplay","");v.muted=true;await v.play();["takePhotoButton","choosePhotoButton"].forEach(photoHideElement);["cameraContainer","capturePhotoButton","closeCameraButton"].forEach(photoShowElement);setPhotoMessage("Camera ready.");return true;}catch(e){console.error("PHOTOS: camera",e);stopPhotoCamera();["takePhotoButton","choosePhotoButton"].forEach(photoShowElement);setPhotoMessage("Could not open the camera. Please choose a photo instead.");return false;}}
function capturePhoto(){const v=photoElement("cameraPreview");if(!v)return setPhotoMessage("Camera preview not found.");if(!v.videoWidth||!v.videoHeight)return setPhotoMessage("Camera is not ready yet.");const c=document.createElement("canvas");c.width=v.videoWidth;c.height=v.videoHeight;const x=c.getContext("2d");if(!x)return setPhotoMessage("Could not capture the photo.");x.drawImage(v,0,0,c.width,c.height);stopPhotoCamera();if(typeof window.processPhotoData!=="function")return setPhotoMessage("Photo processing is not available.");window.processPhotoData(c.toDataURL("image/jpeg",.9));}
function openPhotoFilePicker(){const i=photoElement("photoInput");if(!i)return;i.value="";i.click();}
function handlePhotoFile(e){const i=e&&e.target?e.target:photoElement("photoInput");if(!i||!i.files||!i.files.length)return;const f=i.files[0];if(!f.type||!f.type.startsWith("image/"))return setPhotoMessage("Please choose an image.");const r=new FileReader();r.onload=ev=>{if(typeof window.processPhotoData==="function")window.processPhotoData(ev.target.result);else setPhotoMessage("Photo processing is not available.");};r.onerror=()=>setPhotoMessage("Could not read that photo.");r.readAsDataURL(f);}
function retakePhoto(){FindItPhoto.clearPhoto();const i=photoElement("photoInput");if(i)i.value="";const p=photoElement("photoPreview");if(p)p.src="";photoHideElement("photoPreviewContainer");photoHideElement("submitPhotoButton");setPhotoMessage("");requestAnimationFrame(()=>startPhotoCamera());}
function setupPhotoButtons(){const bind=(id,fn)=>{const e=photoElement(id);if(e)e.onclick=ev=>{ev.preventDefault();fn();};};bind("takePhotoButton",startPhotoCamera);bind("choosePhotoButton",openPhotoFilePicker);bind("capturePhotoButton",capturePhoto);bind("closeCameraButton",()=>{stopPhotoCamera();["cameraContainer","capturePhotoButton","closeCameraButton"].forEach(photoHideElement);["takePhotoButton","choosePhotoButton"].forEach(photoShowElement);});bind("uploadBackButton",closePhotoUpload);bind("submitPhotoButton",()=>{if(typeof window.submitPhoto==="function")window.submitPhoto();});bind("passCategoryButton",()=>{if(typeof window.passPhotoCategory==="function")window.passPhotoCategory();});const i=photoElement("photoInput");if(i)i.onchange=handlePhotoFile;}
document.addEventListener("DOMContentLoaded",()=>{console.log("Find It! photos.js ready");setupPhotoButtons();resetPhotoUI();});
window.openPhotoUpload=openPhotoUpload;window.closePhotoUpload=closePhotoUpload;window.startPhotoCamera=startPhotoCamera;window.stopPhotoCamera=stopPhotoCamera;window.capturePhoto=capturePhoto;window.openPhotoFilePicker=openPhotoFilePicker;window.handlePhotoFile=handlePhotoFile;window.retakePhoto=retakePhoto;window.resetPhotoUpload=resetPhotoUpload;window.resetPhotoUI=resetPhotoUI;window.setPhotoCategory=setPhotoCategory;window.getPhotoCategory=()=>FindItPhoto.getCategory();